
//Log In as admin
POST http://localhost:8080/api/user/authenticate
Content-Type: application/json 

{
    "username": "admin",
    "password": "75885d55-5581-4f46-8d3a-141534d853dd"
}

###
@url = http://localhost:8080/api/user
//Log IN as john
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###
//Log IN as bob
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}


###
//Register, not working yet
POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "joe",
    "password": "P@ssw0rd!"
}

###
//Log in as joe, not in yet
POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "joe",
    "password": "P@ssw0rd!"
}